sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: O7trZrNVxB5X44mAdjJOKTcwSI0UBono0jvfDBuqRsfjVrkvZ7Nfyt6gE7U+WhVmeYkc3zifCFRIfQNqVuPTHxDPb6S4z7bMBXFXtwkROuafk6luhKxT5j335EOq3f3PKsOqgJbvdMjei53J7c/OdGGH06NyZACN0r7u8rch3ebcBua8yxxXVp5sOlpME6X50/EeDNJMv63dPjsI3QSZpmSB+1sV/6ZSavcof9X1HqN1nYoVL9IZoHZg/WMAiguaK/SFOJBR+0wGW21omPyy7pxwCy4DQMlxOUXInIrzyrnBCpEUtdRxg8Rim4GgMhMD9bEiPReqdlHpO01HebRYNJX0G/q1w3Dd1iTAKzyKdJ4N96/AN4bjGH9518enJL7/a0XtdX8ZfwXHDdli400IUYArUKHsGmdCyJmq0SpwAIOyMxgSe8qooZ5Ule15T7faXsfSpxXWHBCZu6KUeF9EDplehB9koQwwBPr3/iToJSrD8r9Pke2eQconu5malCh+RXOZJdHFYOkAGJwHh01DG4YMWRg66dPPLvoxdYPIXVS4r+gwjsIj7A8nBy9yOM0Jx9zkoO4oYZz7HHNrHUtEIqYnOUK9GXEIsLP74pVgyHGg6B6oCeiwlEe0NqAv7gIR2LgtMVkJSTpYhaDxdnckDrKxDS+tRSIwwXcgiCLN5Js=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Historical-Romances-of-Georg-Ebers_5600
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy